services:
  db:
    image: postgres:15
    container_name: subscriptions_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: subscriptions
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./internal/migrations:/docker-entrypoint-initdb.d

  app:
    build: .
    container_name: subscriptions_app
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8080:8080"
    command: ["go", "run", "cmd/main.go"]

volumes:
  db_data:
